server:
  port: 80
spring:
  application:
    name: adon
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/dbadon
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        event:
          merge:
            '[entity_copy_observer]': allow
    show-sql: true
